# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'o_toolkit' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for o_toolkit
  pod 'Firebase/Core'
  pod 'Firebase/Database'
  pod ‘Firebase/Auth’

  target 'o_toolkitTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'o_toolkitUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
